name: claims_app
description: "A flutter app for displaying insurance claims"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_modular:
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1  # Added for Either in clean architecture error handling
  internet_connection_checker: 3.0.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.5.0
  build_runner: ^2.6.0
  http_mock_adapter: ^0.6.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
